name: Manual CI

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print info
        run: |
          echo "Manual CI triggered at $(date -u '+%Y-%m-%d %H:%M:%S') UTC"
          echo "Repo: $GITHUB_REPOSITORY, SHA: $GITHUB_SHA"

