name: Quick Tests (manual)

on:
  workflow_dispatch:

jobs:
  quick-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Build
        run: make build-with-tests

      - name: Run quick tests
        run: make test-quick

